CREATE PROCEDURE dbo.ExecAsDemo
WITH EXECUTE AS 'PriviledgedUser'
AS
BEGIN
        SELECT USER_NAME()
, SUSER_SNAME()
, ORIGINAL_LOGIN()  
END
GO

SELECT USER_NAME(), SUSER_SNAME(), ORIGINAL_LOGIN() ; 

EXEC dbo.ExecAsDemo ;  
